version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_USER: your_username
      POSTGRES_DB: your_database_name
    networks:
      - private-network

  admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@example.com
      PGADMIN_DEFAULT_PASSWORD: your_secure_password
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - private-network

networks:
  private-network:
    driver: bridge
